### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by mbootsman** [10up/wp-local-docker#58] opened 2017-09-07 08:02 UTC
Hi, after installing docker, docker-compose and cloning the Git repo, I run the following command (step 3).

```
$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

Anyone know if this is a bug, or a local problem (for which I would like to have a solution too ;) )

Edit: User is in `docker` group

**Comment by cmmarslender** [comment] 2017-09-20 04:27
@mbootsman Do you have the latest version of docker and docker compose installed? Version 3 is supported with docker 1.13.0+

**Comment by cmmarslender** [comment] 2017-10-09 18:13
If this is still an issue, please let me know. Closing for now.

**Closed as completed by cmmarslender** 2017-10-09 18:13 UTC

**Comment by chrisinmtown** [comment] 2017-10-19 15:15
I see a similar problem when trying to feed a v2.1 docker-compose.yml file to a very recent version of docker, see below.  If I change to just plain 2 it works.  It rejects 3.

```
$ docker-compose --version
docker-compose version 1.8.0, build unknown
$ grep version docker-compose.yml
version: '2.1'
$ docker-compose config
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by cmmarslender** [comment] 2017-10-19 16:31
docker-compose v3 syntax is not supported by docker-compose until version 1.10.0. You'll need to update docker-compose to a newer version to get rid of that error. Current version is 1.16.1

**Comment by deanjpark** [comment] 2017-12-16 02:17
could you tell me how to update docker-compose to a newer version?
I did the command like : sudo apt install docker-compose
$ docker-compose --version
docker-compose version 1.8.0, build unknown
$ grep version docker-compose.yml
version: '3'
$ docker-compose config
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by Viper007Bond** [comment] 2017-12-16 02:21
If you're on Windows or Mac, just install the latest version of Docker.

For Linux, see https://docs.docker.com/compose/install/

**Comment by deanjpark** [comment] 2017-12-16 08:20
Thank you cmmarslender!~
it is a solution to upgrade docker-compose
curl -L https://github.com/docker/compose/releases/download/1.18.0-rc2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by AbadonnaAbbys** [comment] 2018-02-26 17:34
I have latest version of Docker for Windows, but still get error when try to set version 3.

> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `vers
ion` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/


![image](https://user-images.githubusercontent.com/17592321/36685389-4035626c-1b34-11e8-8750-746a87601a49.png)

**Comment by fsaez-ix** [comment] 2018-03-07 18:56
docker --version
Docker version 17.12.1-ce, build 7390fc6

and if I use version 3.1

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by brandonsturgeon** [comment] 2018-04-19 17:00
Getting this error with appropriate docker versions:
```
brandon:dcon/ (master*) $ docker-compose version                                                                                                                                                                                                                                  [9:59:31]
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by iprimo** [comment] 2018-04-27 14:17
Same issue here:

```

cli# docker-compose up -d

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

cli# docker version
Client:
 Version: 18.03.0-ce
 API version:  1.37
 Go version:   go1.9.4
 Git commit:   0520e24
 Built:   Wed Mar 21 23:10:01 2018
 OS/Arch: linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:     18.03.0-ce
  API version: 1.37 (minimum version 1.12)
  Go version:  go1.9.4
  Git commit:  0520e24
  Built:  Wed Mar 21 23:08:31 2018
  OS/Arch:     linux/amd64
  Experimental:     false

cli# docker-compose version
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

```

**Comment by devope** [comment] 2018-06-24 08:48
What should I do? Help me please

**docker -v**
`Docker version 17.12.0-ce, build c97c6d6`

**docker-compose up -d nginx mysql**
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**nano docker-compose.yml**
`version: '3'`

**Comment by cmmarslender** [comment] 2018-07-06 20:48
@devope What version of docker compose are you running? (`docker-compose --version`). You'll need at least version 1.13.0

Install instructions for docker-compose are available here if you need to upgrade. https://docs.docker.com/compose/install/

**Comment by tonyfraser** [comment] 2018-10-05 18:13
I just got the same error.  The Prisma/Scala framework sets the version to "3" in docker-compose.yml. Just edit the file and change the "3" to "2" then it is fine.

brew update docker-compose works for updating.

**Comment by nanisyako** [comment] 2018-10-21 07:57
@tonyfraser , I did your recommendation and it worked.

**Comment by cprkrn** [comment] 2018-12-30 01:00
@tonyfraser worked for me as well, gracias.

**Comment by mohammedyunus009** [comment] 2019-01-17 13:14
**Upgrade your docker** 
`sudo apt upgrade docker-compose` , If that fails then try this [solution](https://stackoverflow.com/questions/36934675/ubuntu-and-updating-docker) .

**Comment by mohammedyunus009** [comment] 2019-01-17 13:54
Its because of older version of docker compose solution  `sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

**Comment by manhphuc** [comment] 2019-02-25 09:58
Just edit the file and change the "3" to "2" then it is fine.

**Comment by antrikshdev** [comment] 2019-03-26 18:25
I had faced the same issue on ubuntu vm.
I did the following steps:
1) sudo apt-get remove docker-compose
2) sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
3)  sudo chmod +x /usr/local/bin/docker-compose
4) sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

I hope this will resolve this issue.
Mine is working

**Comment by mlissner** [comment] 2019-08-27 04:06
If the directions above from @antrikshdev helped, I'm here to tell you that they're probably not what you meant to do. The issue is that if you install with `apt` and run the command, it gets cached in your OS. So then when you uninstall via apt and install a newer version, the link to the old version continues causing issues. 

The instructions above create a link from the apt location to the new location. A better approach is to just delete the cache. To do that, run steps 1-3 above, then delete the cache with:

    hash -d docker-compose

And you should be all set. Read the man file for `hash` if this doesn't make sense.
