### ISSUE TITLE
Add ImageMagick

### ISSUE THREAD

**Issue by Viper007Bond** [10up/wp-local-docker#62] opened 2017-11-21 05:03 UTC
It'd be useful to have ImageMagick for testing purposes.

(I tried to install it myself but I suck at Linux too much to do it.)

**Comment by cmmarslender** [comment] 2017-11-21 17:20
Duplicate of #43 - I'll see if I can get this added today.

**Closed as completed by cmmarslender** 2017-11-21 17:20 UTC

**Comment by cmmarslender** [comment] 2017-11-21 18:38
Latest [phpfpm images](https://github.com/10up/phpfpm-image) now come with ImageMagick.

**Comment by Viper007Bond** [comment] 2017-11-21 22:21
Thanks and sorry for not searching first!
